name: lobium-landing-page
region: nyc
services:
  - name: web
    image: ghcr.io/lobium-soft/lobium-landing-page/lobium-landing-page:latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-d-1vcpu-4gb
    routes:
      - path: /
    source_dir: /
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
