name: lobium-landing-page
region: nyc
services:
  - name: web
    image: 
      registry_type: GHCR
      registry: lobium-soft
      repository: lobium-landing-page
      tag: latest
      registry_credentials: "${github_username}:${github_token}"
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-d-1vcpu-4gb
    routes:
      - path: /
    source_dir: /
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
