name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Build and Deploy to DigitalOcean App Platform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/lobium-landing-page
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      # Use pre-created app.yaml file in repo
      - name: Verify app.yaml exists
        run: |
          if [ ! -f ".do/app.yaml" ]; then
            echo "Error: .do/app.yaml file not found!"
            echo "Please make sure the file exists in your repository."
            exit 1
          else
            echo "Found app.yaml file, proceeding with deployment."
            cat .do/app.yaml
          fi
      
      - name: Create GitHub Registry Credentials in DigitalOcean
        run: |
          # Create or update GitHub credentials as DO secrets
          # First, check if the secrets exist already
          APP_ID=$(doctl apps list --no-header --format ID,Spec.Name | grep lobium-landing-page | awk '{print $1}' || echo "")
          
          if [ -z "$APP_ID" ]; then
            echo "App doesn't exist yet, will create secrets during app creation."
          else
            echo "Setting up GitHub registry credentials as secrets..."
            
            # Create or update the GitHub username secret
            doctl apps create-secret $APP_ID \
              --key github_username \
              --value ${{ github.actor }} \
              --scope APP \
              --replace
            
            # Create or update the GitHub token secret
            doctl apps create-secret $APP_ID \
              --key github_token \
              --value ${{ secrets.GITHUB_TOKEN }} \
              --scope APP \
              --replace
              
            echo "Secrets created successfully!"
          fi
      
      - name: Deploy to App Platform
        run: |
          # Check if app already exists
          APP_ID=$(doctl apps list --no-header --format ID,Spec.Name | grep lobium-landing-page | awk '{print $1}')
          
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.yaml --wait
          else
            echo "Updating existing app..."
            doctl apps update $APP_ID --spec .do/app.yaml --wait
          fi
      
      - name: Get App URL
        run: |
          APP_ID=$(doctl apps list --no-header --format ID,Spec.Name | grep lobium-landing-page | awk '{print $1}')
          APP_URL=$(doctl apps get $APP_ID --format DefaultIngress | grep -v 'DEFAULT INGRESS')
          
          echo "Application deployed successfully!"
          echo "Your app is available at: https://$APP_URL"
