name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - deploy-digital-app

jobs:
  deploy:
    name: Deploy to DigitalOcean App Platform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Create app.yaml if it doesn't exist
        run: |
          if [ ! -f ".do/app.yaml" ]; then
            mkdir -p .do
            cat > .do/app.yaml << 'EOF'
              name: lobium-landing-page
              region: nyc
              services:
                - name: web
                  dockerfile_path: Dockerfile
                  github:
                    branch: deploy
                    repo: ${{ github.repository }}
                  http_port: 8080
                  instance_count: 1
                  instance_size_slug: basic-xxs
                  routes:
                    - path: /
              alerts:
                - rule: DEPLOYMENT_FAILED
                - rule: DOMAIN_FAILED
            EOF
            
            echo "Created app.yaml configuration file"
          else
            echo "app.yaml already exists"
          fi
          
      - name: Deploy to App Platform
        run: |
          # Check if app already exists
          APP_ID=$(doctl apps list --no-header --format ID,Spec.Name | grep lobium-landing-page | awk '{print $1}')
          
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.yaml --wait
          else
            echo "Updating existing app..."
            doctl apps update $APP_ID --spec .do/app.yaml --wait
          fi
          
      - name: Get App URL
        run: |
          APP_ID=$(doctl apps list --no-header --format ID,Spec.Name | grep lobium-landing-page | awk '{print $1}')
          APP_URL=$(doctl apps get $APP_ID --format DefaultIngress | grep -v 'DEFAULT INGRESS')
          
          echo "Application deployed successfully!"
          echo "Your app is available at: https://$APP_URL"
